# Generated by Django 4.2.10 on 2024-03-24 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('type', models.CharField(choices=[('Full-Time', 'Full Time'), ('Part-Time', 'Part Time')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
